apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cybercyclops-com-tls
spec:
  secretName: cybercyclops-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: cybercyclops.com
  dnsNames:
    - cybercyclops.com
    - www.cybercyclops.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - cybercyclops.com
          - www.cybercyclops.com
