apiVersion: certmanager.ks8.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'yevhen.grinman@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
